// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvTMA4iLLLpuK6Oedg4xIWqatEvFTKE_4',
    appId: '1:404505336223:web:c68412e52807c926b545aa',
    messagingSenderId: '404505336223',
    projectId: 'vybe-bata-c07aa',
    authDomain: 'vybe-bata-c07aa.firebaseapp.com',
    storageBucket: 'vybe-bata-c07aa.firebasestorage.app',
    measurementId: 'G-VMR31G0BSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmyU3TuQwx8fSqzJy5KlgBG4M6NQI-JOc',
    appId: '1:404505336223:android:9765790c109a14e3b545aa',
    messagingSenderId: '404505336223',
    projectId: 'vybe-bata-c07aa',
    storageBucket: 'vybe-bata-c07aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf-GS6Msp01ps7-Jvaua216DutifNqMiQ',
    appId: '1:404505336223:ios:efc994b69fc22384b545aa',
    messagingSenderId: '404505336223',
    projectId: 'vybe-bata-c07aa',
    storageBucket: 'vybe-bata-c07aa.firebasestorage.app',
    iosBundleId: 'com.justinchoi.vybe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf-GS6Msp01ps7-Jvaua216DutifNqMiQ',
    appId: '1:404505336223:ios:efc994b69fc22384b545aa',
    messagingSenderId: '404505336223',
    projectId: 'vybe-bata-c07aa',
    storageBucket: 'vybe-bata-c07aa.firebasestorage.app',
    iosBundleId: 'com.justinchoi.vybe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvTMA4iLLLpuK6Oedg4xIWqatEvFTKE_4',
    appId: '1:404505336223:web:5a67b4f52624aaf7b545aa',
    messagingSenderId: '404505336223',
    projectId: 'vybe-bata-c07aa',
    authDomain: 'vybe-bata-c07aa.firebaseapp.com',
    storageBucket: 'vybe-bata-c07aa.firebasestorage.app',
    measurementId: 'G-F6WDCGFGJ1',
  );

}